model_configs:
  model_name: 'BAAI/bge-large-en-v1.5'
data_configs:
  sentences_path: 'data/testing_data/bank_test.txt'
  output_path: 'output/test_embeddings'
experiment_configs:
  model_batch_size: 32
  context_window: None
  target_word: 'bank'