model:
  model_name: 'bert-large-uncased'
data:
  sentences_path: 'data/bnc_spoken.txt'
  output_path: 'output'
experiment:
  model_batch_size: 32
  context_window: 40
  target_word: 'duty'
metrics:
  anisotropy_correction: False
  layers: 'all'
  metrics: ['similarity_matrix', 'mev', 'inter_similarity', 'intra_similarity', 'average_similarity', 'similarity_std']
landscapes:
  pca_min: 2
  pca_max: 5
  pca_step: 1
  cluster_min: 2
  cluster_max: 5
  cluster_step: 1
  generate_all: True
  save_optimization: True