model:
  model_name: 'bert-base-uncased'
data:
  sentences_path: 'data/testing_data/bank_test.txt'
  output_path: 'output/test_embeddings'
experiment:
  model_batch_size: 32
  context_window: None
  target_word: 'bank'