model:
  model_name: 'Alibaba-NLP/gte-base-en-v1.5'
data:
  sentences_path: 'data/bnc_spoken.txt'
  output_path: 'output'
experiment:
  model_batch_size: 32
  context_window: None
  target_word: 'duty'